### ISSUE TITLE
move_units_oob todo

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/data-workflows#24]
- [x] Fill out test data with needed design links and units info
- [x] Driver doesn't correctly send file locations to L1_normalize
- [x] Clean up L1_normalize processing output
- [x] Check L1a functionality
