### ISSUE TITLE
L1 beta checklist

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/data-workflows#49]
Synthesized from the [Google doc](https://docs.google.com/document/d/1a4X0iuVeJUC1z-NWjlKSjMKxrAzloHmhS_BUSex80LA/edit?usp=sharing)

**Feedback from SP/RR/SC**

- [x] Use site codes from [sample planning document](https://docs.google.com/spreadsheets/d/1-HLIjkx17gid0L81dvBoCiUqoqSDnUgoTA8m0w-zzPI/edit#gid=152374833) #50 
- [x] I removed units (available in metadata) and old_value (available in L0); remove `Site` column too? @stephpenn1  It's available in filename...but maybe this would be a pain for users
- [x] Improve template files so they look 'real' #51 

**Feedback from PR and others**

- [ ] Finish instrument bounds and units in [schema template](https://docs.google.com/spreadsheets/d/1ikOlTPCrrLe46Sn9ICS2hJ_5uV6Aav9k2kx_ChshHoQ/edit#gid=2056809878)
- [ ] Flag cleanup (see SP's notes in google doc)

**Comment by bpbond** [comment]
Current file format:

<img width="745" alt="Screenshot 2023-11-02 at 3 37 48 PM" src="https://github.com/COMPASS-DOE/data-workflows/assets/1956468/7a7e6763-eae1-4ec3-a365-509ed5e2bef9">

**Comment by stephpenn1** [comment]
> I removed units (available in metadata) and old_value (available in L0); remove Site column too? @stephpenn1 It's available in filename...but maybe this would be a pain for users

- Units: I think we should make the unit format a question on the beta google form (i.e should we put them in the variable name, keep as separate column, or put into metadata file)
- Site: it's in the design link too, so I'm more inclined to remove this column

**Comment by stephpenn1** [comment]
not sure if we've added this in, but an additional L1 flag could be the -99999 reading on certain sensors (see meeting [doc](https://docs.google.com/document/d/1rIgVzDFjGVDUKIytWGx_l7pbgsuMGnNrDPKZOsTzIBI/edit?usp=sharing))

**Comment by bpbond** [comment]
- [ ] Metadata files need to specify what the NA value is

**Comment by bpbond** [comment]
We're good here
