### ISSUE TITLE
Major outcomes from L1 feedback meeting 2023-11-29

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/data-workflows#59]
- [ ] Significant preference for units as part of research_name (e.g. `soil_vwc_10cm_degC`). Roy and Ben both groan :) but many find this a lot easier! At that point I might vote just to restore the `units` column
- [x] Have L1 data include basic visualizations for all variables #61 
- [x] Include OOB limit values in metadata #62 
- [x] How to handle out-of-service events recorded by techs? 
- [x] BBL and SP to work towards design_link tables for all sites #63 #68 
- [x] Want a mechanism to handle the issue of e.g. sapflux sensor being shifted to a new tree after original dies -- basically need a `valid_through` column in design link table and code to handle that #60 
- [ ] RR gave good example of hierarchical flag: fluctuating voltage flag should cascade to inform all sensors on that datalogger

**Comment by bpbond** [comment]
Hierarchy examples
*  Fluctuating voltage flag should cascade to inform all sensors on that datalogger
* Does a bad TEROS temperature reading informs VWC and EC on same probe?

**Comment by bpbond** [comment]
Hierarchy. With the addition of a single `parent` column in the design_link table, we can do something like this:

<img width="682" alt="Screenshot 2023-12-01 at 6 22 54 AM" src="https://github.com/COMPASS-DOE/data-workflows/assets/1956468/9a21c0b3-d160-477b-8760-88efd5b98985">

This visualizes how a flag on the solar battery voltage would flow (propagate) to the sapflow, TEROS, and AquaTroll sensors.
